name: stock_management
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^0.6.7
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  flutter_riverpod: ^0.12.1
  get_it: ^5.0.1
  lottie: ^0.7.0+1
  shared_preferences: ^0.5.12+2
  moor_flutter: ^3.1.0
  path_provider: ^1.6.14
  path: ^1.7.0
  shimmer: ^1.1.2

dev_dependencies: 
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.7
  moor_generator:
  build_runner: null
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/lottie/
    - i18n/
  fonts:
    - family: NanumGothic-Bold
      fonts:
        - asset: assets/fonts/NanumGothic-Bold.ttf
    - family: NanumGothic-Regular
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf